In [1]:
import pandas as pd

df = pd.read_csv("fish_all.csv")

In [2]:
df.head()

Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

In [3]:
df['Species'].value_counts()

Perch        56
Bream        35
Roach        20
Pike         17
Smelt        14
Parkki       11
Whitefish     6
Name: Species, dtype: int64

In [4]:
df.loc[df['Species']=='Perch','Species'] = 0
df.loc[df['Species']=='Bream','Species'] = 1
df.loc[df['Species']=='Roach','Species'] = 2
df.loc[df['Species']=='Pike','Species'] = 3
df.loc[df['Species']=='Smelt','Species'] = 4
df.loc[df['Species']=='Parkki','Species'] = 5
df.loc[df['Species']=='Whitefish','Species'] = 6
df['Species'] = df['Species'].astype(int)

In [5]:
feature = df[df.keys().drop('Species')]
outcome = df['Species']

In [6]:
from sklearn.model_selection import train_test_split

train_feature, test_feature, train_target, test_target = train_test_split(feature,outcome,random_state=42, stratify=outcome)

In [7]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier()
clf.fit(train_feature, train_target)

RandomForestClassifier()

In [8]:
y_pred = clf.predict(test_feature)

In [9]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

print("Accuracy :",accuracy_score(test_target, y_pred))
print(confusion_matrix(test_target, y_pred,labels=[6,5,4,3,2,1,0]))

Accuracy : 0.825
[[ 1  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  1]
 [ 0  0  3  0  0  0  1]
 [ 0  0  0  4  0  0  0]
 [ 0  0  0  0  2  0  3]
 [ 0  0  0  0  0  9  0]
 [ 0  0  0  0  2  0 12]]


In [10]:
from sklearn.linear_model import LogisticRegression

clf2 = LogisticRegression(max_iter=1000000)
clf2.fit(train_feature, train_target)

/home/minsuchae/.pyenv/versions/3.9.0/envs/tensorflow_gpu_2.7.0/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of f AND g EVALUATIONS EXCEEDS LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(max_iter=1000000)

In [11]:
y_pred = clf2.predict(test_feature)

In [12]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

print("Accuracy :",accuracy_score(test_target, y_pred))
print(confusion_matrix(test_target, y_pred,labels=[6,5,4,3,2,1,0]))

Accuracy : 0.9
[[ 0  0  0  0  1  0  0]
 [ 0  3  0  0  0  0  0]
 [ 0  0  4  0  0  0  0]
 [ 0  0  0  4  0  0  0]
 [ 0  0  0  0  3  1  1]
 [ 0  0  0  0  0  9  0]
 [ 0  0  0  1  0  0 13]]


In [13]:
from sklearn.tree import DecisionTreeClassifier

clf3 = DecisionTreeClassifier()
clf3.fit(train_feature, train_target)

DecisionTreeClassifier()

In [14]:
y_pred = clf3.predict(test_feature)

In [15]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

print("Accuracy :",accuracy_score(test_target, y_pred))
print(confusion_matrix(test_target, y_pred,labels=[6,5,4,3,2,1,0]))

Accuracy : 0.675
[[0 0 0 0 1 0 0]
 [0 3 0 0 0 0 0]
 [0 0 4 0 0 0 0]
 [0 0 0 3 0 0 1]
 [0 0 0 0 2 0 3]
 [0 0 0 0 1 8 0]
 [2 0 0 0 4 1 7]]


In [16]:
from sklearn.svm import SVC

clf4 = SVC()
clf4.fit(train_feature, train_target)

SVC()

In [17]:
y_pred = clf4.predict(test_feature)

In [18]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

print("Accuracy :",accuracy_score(test_target, y_pred))
print(confusion_matrix(test_target, y_pred,labels=[6,5,4,3,2,1,0]))

Accuracy : 0.4
[[ 0  0  0  0  0  0  1]
 [ 0  0  0  0  0  0  3]
 [ 0  0  0  0  0  0  4]
 [ 0  0  0  0  0  3  1]
 [ 0  0  0  0  0  1  4]
 [ 0  0  0  0  0  5  4]
 [ 0  0  0  0  0  3 11]]


In [19]:
from sklearn.ensemble import VotingClassifier

clf5 = VotingClassifier([
                         ('dt',DecisionTreeClassifier()),
                         ('lr',LogisticRegression(max_iter=1000000)),
                         ('rf',RandomForestClassifier()),
                         ('svm',SVC())],
                        voting='hard', n_jobs=-1)

In [20]:
clf5.fit(train_feature, train_target)

/home/minsuchae/.pyenv/versions/3.9.0/envs/tensorflow_gpu_2.7.0/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of f AND g EVALUATIONS EXCEEDS LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


VotingClassifier(estimators=[('dt', DecisionTreeClassifier()),
                             ('lr', LogisticRegression(max_iter=1000000)),
                             ('rf', RandomForestClassifier()), ('svm', SVC())],
                 n_jobs=-1)

In [21]:
y_pred = clf5.predict(test_feature)

In [22]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

print("Accuracy :",accuracy_score(test_target, y_pred))
print(confusion_matrix(test_target, y_pred,labels=[6,5,4,3,2,1,0]))

Accuracy : 0.85
[[ 0  0  0  0  0  0  1]
 [ 0  2  0  0  0  0  1]
 [ 0  0  3  0  0  0  1]
 [ 0  0  0  4  0  0  0]
 [ 0  0  0  0  2  0  3]
 [ 0  0  0  0  0  9  0]
 [ 0  0  0  0  0  0 14]]


In [23]:
from sklearn.ensemble import StackingClassifier

clf6 = StackingClassifier(estimators=[('dt',DecisionTreeClassifier()),
                                      ('lr',LogisticRegression(max_iter=1000000)),
                                      ('rf',RandomForestClassifier(n_jobs=-1)),
                                      ('svm',SVC())],
                          final_estimator=LogisticRegression(max_iter=1000000), n_jobs=-1)

In [24]:
clf6.fit(train_feature, train_target)

/home/minsuchae/.pyenv/versions/3.9.0/envs/tensorflow_gpu_2.7.0/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of f AND g EVALUATIONS EXCEEDS LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/minsuchae/.pyenv/versions/3.9.0/envs/tensorflow_gpu_2.7.0/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of f AND g EVALUATIONS EXCEEDS LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alt

StackingClassifier(estimators=[('dt', DecisionTreeClassifier()),
                               ('lr', LogisticRegression(max_iter=1000000)),
                               ('rf', RandomForestClassifier(n_jobs=-1)),
                               ('svm', SVC())],
                   final_estimator=LogisticRegression(max_iter=1000000),
                   n_jobs=-1)

In [25]:
y_pred = clf6.predict(test_feature)

In [26]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

print("Accuracy :",accuracy_score(test_target, y_pred))
print(confusion_matrix(test_target, y_pred,labels=[6,5,4,3,2,1,0]))

Accuracy : 0.95
[[ 1  0  0  0  0  0  0]
 [ 0  3  0  0  0  0  0]
 [ 0  0  4  0  0  0  0]
 [ 0  0  0  4  0  0  0]
 [ 0  0  0  0  3  1  1]
 [ 0  0  0  0  0  9  0]
 [ 0  0  0  0  0  0 14]]


In [27]:
from xgboost import XGBClassifier
from xgboost.callback import EarlyStopping
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC


class MultiLayerStacking:
    def __init__(self):
        self.layer_one_dt = DecisionTreeClassifier()
        self.layer_one_lr = LogisticRegression(max_iter=1000000)
        self.layer_one_rf = RandomForestClassifier(n_jobs=-1)
        self.layer_one_svm = SVC()
        
        self.layer_two_rf = RandomForestClassifier(n_jobs=-1)
        self.layer_two_xgboost = XGBClassifier()
                          
        self.layer_final = LogisticRegression(max_iter=1000000)
                          
    def fit(self, feature, target):
        self.layer_one_dt.fit(feature,target)
        self.layer_one_lr.fit(feature,target)
        self.layer_one_rf.fit(feature,target)
        self.layer_one_svm.fit(feature,target)
                          
        pred_layer_one_dt = self.layer_one_dt.predict(feature).reshape(-1,1)
        pred_layer_one_lr = self.layer_one_lr.predict(feature).reshape(-1,1)
        pred_layer_one_rf = self.layer_one_rf.predict(feature).reshape(-1,1)
        pred_layer_one_svm = self.layer_one_svm.predict(feature).reshape(-1,1)
        
        input_layer_two = np.concatenate([pred_layer_one_dt,pred_layer_one_lr,pred_layer_one_rf,pred_layer_one_svm], axis=1)
        train_feature, val_feature, train_target, val_target = train_test_split(input_layer_two, target, stratify=target, random_state = 42)
        
        self.layer_two_rf.fit(input_layer_two, target)
        
        early_stop = EarlyStopping(rounds=30,metric_name='merror',data_name="validation_0",save_best=True)        
        self.layer_two_xgboost.fit(train_feature, train_target, eval_set=[(val_feature,val_target)], eval_metric='merror',callbacks=[early_stop], verbose=False)
        
        pred_layer_two_rf = self.layer_two_rf.predict(input_layer_two).reshape(-1,1)
        pred_layer_two_xgboost = self.layer_two_xgboost.predict(input_layer_two).reshape(-1,1)
        
        input_layer_last = np.concatenate([pred_layer_two_rf,pred_layer_two_xgboost], axis=1)
        self.layer_final.fit(input_layer_last,target)
        
    def predict(self, feature):
        pred_layer_one_dt = self.layer_one_dt.predict(feature).reshape(-1,1)
        pred_layer_one_lr = self.layer_one_lr.predict(feature).reshape(-1,1)
        pred_layer_one_rf = self.layer_one_rf.predict(feature).reshape(-1,1)
        pred_layer_one_svm = self.layer_one_svm.predict(feature).reshape(-1,1)
        
        input_layer_two = np.concatenate([pred_layer_one_dt,pred_layer_one_lr,pred_layer_one_rf,pred_layer_one_svm], axis=1)
        
        pred_layer_two_rf = self.layer_two_rf.predict(input_layer_two).reshape(-1,1)
        pred_layer_two_xgboost = self.layer_two_xgboost.predict(input_layer_two).reshape(-1,1)
        
        input_layer_last = np.concatenate([pred_layer_two_rf,pred_layer_two_xgboost], axis=1)
        return self.layer_final.predict(input_layer_last)

In [28]:
clf7 = MultiLayerStacking()

In [29]:
clf7.fit(train_feature, train_target)

/home/minsuchae/.pyenv/versions/3.9.0/envs/tensorflow_gpu_2.7.0/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of f AND g EVALUATIONS EXCEEDS LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/minsuchae/.pyenv/versions/3.9.0/envs/tensorflow_gpu_2.7.0/lib/python3.9/site-packages/xgboost/sklearn.py:861: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(
/home/minsuchae/.pyenv/versions/3.9.0/envs/tensorflow_gpu_2.7.0/lib/python3.9/site-packages/xgboost/sklearn.py:861: UserWarning: `callbac

In [30]:
y_pred = clf7.predict(test_feature)

In [31]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

print("Accuracy :",accuracy_score(test_target, y_pred))
print(confusion_matrix(test_target, y_pred,labels=[6,5,4,3,2,1,0]))

Accuracy : 0.7
[[0 0 0 0 1 0 0]
 [0 3 0 0 0 0 0]
 [0 0 3 0 1 0 0]
 [0 0 0 3 0 0 1]
 [0 0 0 1 2 0 2]
 [0 0 0 0 0 9 0]
 [0 0 0 0 4 2 8]]
