In [1]:
import pandas as pd

df = pd.read_csv("fish_all.csv")

In [2]:
df.head()

Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

In [3]:
df['Species'].value_counts()

Perch        56
Bream        35
Roach        20
Pike         17
Smelt        14
Parkki       11
Whitefish     6
Name: Species, dtype: int64

In [4]:
df.loc[df['Species']=='Perch','Species'] = 0
df.loc[df['Species']=='Bream','Species'] = 1
df.loc[df['Species']=='Roach','Species'] = 2
df.loc[df['Species']=='Pike','Species'] = 3
df.loc[df['Species']=='Smelt','Species'] = 4
df.loc[df['Species']=='Parkki','Species'] = 5
df.loc[df['Species']=='Whitefish','Species'] = 6
df['Species'] = df['Species'].astype(int)

In [5]:
feature = df[df.keys().drop('Species')]
outcome = df['Species']

In [6]:
from sklearn.model_selection import train_test_split

train_feature, test_featue, train_target, test_target = train_test_split(feature,outcome,random_state=42, stratify=outcome)

In [7]:
from sklearn.ensemble import AdaBoostClassifier

clf = AdaBoostClassifier()
clf.fit(train_feature, train_target)

AdaBoostClassifier()

In [8]:
y_pred = clf.predict(test_featue)

In [9]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

print("Accuracy :",accuracy_score(test_target, y_pred))
print(confusion_matrix(test_target, y_pred,labels=[6,5,4,3,2,1,0]))

Accuracy : 0.45
[[0 0 0 0 1 0 0]
 [0 0 0 0 3 0 0]
 [0 0 0 0 0 0 4]
 [0 0 0 0 0 0 4]
 [0 0 0 0 4 0 1]
 [0 0 0 0 0 9 0]
 [1 0 0 0 8 0 5]]


In [10]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import AdaBoostClassifier
import numpy as np

clf2 = AdaBoostClassifier()
parameters = {'n_estimators':np.arange(100,151,1),'learning_rate':np.arange(0.5,2.1,0.1),'algorithm':['SAMME','SAMME.R']}
grid_search = GridSearchCV(clf2, param_grid=parameters, cv=5, n_jobs=-1,scoring='accuracy')

In [11]:
grid_search.fit(train_feature, train_target)

GridSearchCV(cv=5, estimator=AdaBoostClassifier(), n_jobs=-1,
             param_grid={'algorithm': ['SAMME', 'SAMME.R'],
                         'learning_rate': array([0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7,
       1.8, 1.9, 2. ]),
                         'n_estimators': array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])},
             scoring='accuracy')

In [12]:
grid_search.best_params_

{'algorithm': 'SAMME',
 'learning_rate': 1.5999999999999996,
 'n_estimators': 137}

In [13]:
clf2 = grid_search.best_estimator_

In [14]:
y_pred = clf2.predict(test_featue)

In [15]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

print("Accuracy :",accuracy_score(test_target, y_pred))
print(confusion_matrix(test_target, y_pred,labels=[6,5,4,3,2,1,0]))

Accuracy : 0.625
[[0 0 0 0 0 0 1]
 [0 3 0 0 0 0 0]
 [0 0 4 0 0 0 0]
 [0 0 0 2 0 0 2]
 [1 1 0 0 0 0 3]
 [0 0 0 0 0 9 0]
 [3 2 0 0 0 2 7]]
